### ISSUE TITLE
Team 2 | Final Project | Inserting Images and GIFs

### ISSUE THREAD

**Issue by CatVidia** [CodeChica/SparkleHub-lite#48]
**First Steps:: Work Period1:**

1. Looking at other examples and finding inspiration
2. Designing what we would like the SparkleHub website to look like in the end
3. Researching on what we should code

**Wireframe :**

1. First image Displays how to open or have the option to upload images.
2. The Second image displays how the image would look with your text.
3. Image Three displays how the image would look if you click sparkle attached with a sparkle.

![193421480-66450e6e-c514-40c6-95e2-895ca8bbc9f5](https://user-images.githubusercontent.com/97800989/193422263-236482c5-3fd9-4b7d-82d2-2dc794d56bac.jpg)
![image](https://user-images.githubusercontent.com/97800989/193422285-74c36a36-c87c-4169-b7ef-d083d4410c08.png)
![image](https://user-images.githubusercontent.com/97800989/193422291-b4b52796-774c-4985-bcd3-9170e4972361.png)

**Sample Code For Opening File Explorer:**
![image](https://user-images.githubusercontent.com/97800989/193422213-27c0748b-4429-456d-8d23-d561302d664a.png)

**Comment by CatVidia** [comment]
Wireframe is made by Beth

**Comment by Bethsalazar15** [comment]
Updates from Kellyn:

 move wireframes and user story into a separate issue
 construct the user story / put into the new issue
 tasks list

**Comment by CatVidia** [comment]
**User Story:**

  As a Sparkler,
    I want to insert images and GIFs,
    so that I can express what I'm trying to say in a new and different way.

**Acceptance Criteria:**

  * [ ] There must be a small button so that the Sparkler can insert a file
  * [ ] The image must be under the text the sparkler is saying in a size which is not too big or small
  * [ ] The Sparkler must only be able to insert one image/GIF at a time

**Comment by CatVidia** [comment]
**Task Breakdown Summary**

- [ ] Research all the needed information to code the final product successfully
- [ ] Choose button icon image (match the color scheme of the SparkleHub page)
- [ ] Code button image
- [ ] Code CSS
- [ ] Test the result and make sure that it works on all platforms

Bonus: If we have time, we can also see if code it to adjust how it would look on mobile
